# This is a basic workflow to help you get started with Actions

name: Discord Message

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    discord:
      runs-on: ubuntu-latest
      steps:
        - name: Discord notification
          uses: Sniddl/discord-commits@v1.2
          with:
            webhook: ${{secrets.DISCORD_WEBHOOK}}
            message: '**{{ github.context.payload.repository.name }}** has a new commit'
            embed:  '[{{"title": "{{ commit.title }}", "color":1432397}, "description":"{{commit.description}}", "author": { "name": "{{ commit.author.name }} ({{ commit.author.username }})"}}]'
